language: python
python:
- "3.6"

services:
  - postgresql

addons:
  postgresql: "9.4"
  
before_script:
  - psql -c 'create database fpost;' -U postgres
  - psql -c "ALTER USER postgres WITH PASSWORD 'secret'" -d template1 -U postgres
  - psql -c 'create table if not exists post (title varchar, name varchar, text varchar);' -U postgres  
  
install: "pip install -r requirements.txt"

script:
- python test/unit.py