language: python
python:
- "3.6"

services:
  - postgresql
  
addons:
  postgresql: "9.4"
  
before_script:
  - psql -c 'create database fpost;' -U postgres
  - psql -c "ALTER USER postgres WITH PASSWORD 'secret'" -d template1 -U postgres
  - psql -c 'create table if not exists post (title varchar, name varchar, text varchar);' -U postgres
  
install: "pip install -r requirements.txt"

script:
- pip install chromedriver_installer==0.0.6 \
	--install-option="--chromedriver-version=2.10" \
    --install-option="--chromedriver-checksums=4fecc99b066cb1a346035bf022607104,058cd8b7b4b9688507701b5e648fd821"
- cd ./test
- python unit.py
- python main.py &
- cd ..
- cd ./features
- behave fpost.feature 
